
// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
/*
***********************************************************/
package Accessibilita.AccessiBG_Backend;

public class Piano {

	public int numero;
	private String descrizione;
	
	public Piano(int numero, String descrizione) {
		this.numero = numero;
		this.descrizione = descrizione;
	}
	
	public int getNumero() { return numero; }
    public void setNumero(int numero) { this.numero = numero; }

    public String getDescrizione() { return descrizione; }
    public void setDescrizione(String descrizione) { this.descrizione = descrizione;}
}
