
// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
/*
package AccessiBG_ClassDiagram;



***********************************************************/

package Accessibilita.AccessiBG_Backend;


public enum TipoParcheggio {
	LIBERO,
	A_PAGAMENTO,
	DISCO_ORARIO
}
