
// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
/*
package AccessiBG_ClassDiagram;



*
package struttura;

/**
 * 

public class Bar extends Stanza

 {
	private String orario;

	
	public Bar(String descrizione, boolean accessibile, String orario) {
		super(descrizione, accessibile);
		this.orario = orario;
	}
	
	public Bar() { super(); }
	
	public String getOrario() { return orario; }
    public void setOrario(String orario) { this.orario = orario; }
}
*/