/*
 * This file is generated by jOOQ.
 */
package accessibilita.genjooq.tables;


import accessibilita.genjooq.DefaultSchema;
import accessibilita.genjooq.tables.records.EdificioRecord;

import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Edificio extends TableImpl<EdificioRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>Edificio</code>
     */
    public static final Edificio EDIFICIO = new Edificio();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EdificioRecord> getRecordType() {
        return EdificioRecord.class;
    }

    /**
     * The column <code>Edificio.NOME</code>.
     */
    public final TableField<EdificioRecord, String> NOME = createField(DSL.name("NOME"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>Edificio.INDIRIZZO</code>.
     */
    public final TableField<EdificioRecord, String> INDIRIZZO = createField(DSL.name("INDIRIZZO"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>Edificio.SEDE</code>.
     */
    public final TableField<EdificioRecord, String> SEDE = createField(DSL.name("SEDE"), SQLDataType.CLOB, this, "");

    private Edificio(Name alias, Table<EdificioRecord> aliased) {
        this(alias, aliased, null);
    }

    private Edificio(Name alias, Table<EdificioRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>Edificio</code> table reference
     */
    public Edificio(String alias) {
        this(DSL.name(alias), EDIFICIO);
    }

    /**
     * Create an aliased <code>Edificio</code> table reference
     */
    public Edificio(Name alias) {
        this(alias, EDIFICIO);
    }

    /**
     * Create a <code>Edificio</code> table reference
     */
    public Edificio() {
        this(DSL.name("Edificio"), null);
    }

    public <O extends Record> Edificio(Table<O> child, ForeignKey<O, EdificioRecord> key) {
        super(child, key, EDIFICIO);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Edificio as(String alias) {
        return new Edificio(DSL.name(alias), this);
    }

    @Override
    public Edificio as(Name alias) {
        return new Edificio(alias, this);
    }

    @Override
    public Edificio as(Table<?> alias) {
        return new Edificio(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Edificio rename(String name) {
        return new Edificio(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Edificio rename(Name name) {
        return new Edificio(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Edificio rename(Table<?> name) {
        return new Edificio(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super String, ? super String, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super String, ? super String, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
