// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
/*
package AccessiBG_ClassDiagram;



***********************************************************/
package servizi;

/**
 * 
 */
public enum ServiziPiano {
	/**
	 * 
	 */
	MACCHINETTE,
	/**
	 * 
	 */
	DISTRIBUTOREACQUA,
	/**
	 * 
	 */
	ASCENSORE
	;
}
