// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
/*
package AccessiBG_ClassDiagram;



***********************************************************/
package servizi;

/**
 * 
 */
public class ServiziRistoro {
				/**
				 * 
				 */
				public ServiziPiano tipo;
				/**
				 * 
				 */
				public boolean fuoriServizio;
				/**
				 * 
				 */
				public String accesPulsantiera;
	/**
	 * 
	 */
	public void segnalaGuasto() {
	}
}
