/*
 * This file is generated by jOOQ.
 */
package accessibilita.genjooq.tables.records;


import accessibilita.genjooq.tables.Edificio2;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Edificio2Record extends TableRecordImpl<Edificio2Record> implements Record4<String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>Edificio2.NOME</code>.
     */
    public void setNome(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>Edificio2.NOME</code>.
     */
    public String getNome() {
        return (String) get(0);
    }

    /**
     * Setter for <code>Edificio2.INDIRIZZO</code>.
     */
    public void setIndirizzo(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>Edificio2.INDIRIZZO</code>.
     */
    public String getIndirizzo() {
        return (String) get(1);
    }

    /**
     * Setter for <code>Edificio2.SEDE</code>.
     */
    public void setSede(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>Edificio2.SEDE</code>.
     */
    public String getSede() {
        return (String) get(2);
    }

    /**
     * Setter for <code>Edificio2.IMAGE_URL</code>.
     */
    public void setImageUrl(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>Edificio2.IMAGE_URL</code>.
     */
    public String getImageUrl() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<String, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<String, String, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Edificio2.EDIFICIO2.NOME;
    }

    @Override
    public Field<String> field2() {
        return Edificio2.EDIFICIO2.INDIRIZZO;
    }

    @Override
    public Field<String> field3() {
        return Edificio2.EDIFICIO2.SEDE;
    }

    @Override
    public Field<String> field4() {
        return Edificio2.EDIFICIO2.IMAGE_URL;
    }

    @Override
    public String component1() {
        return getNome();
    }

    @Override
    public String component2() {
        return getIndirizzo();
    }

    @Override
    public String component3() {
        return getSede();
    }

    @Override
    public String component4() {
        return getImageUrl();
    }

    @Override
    public String value1() {
        return getNome();
    }

    @Override
    public String value2() {
        return getIndirizzo();
    }

    @Override
    public String value3() {
        return getSede();
    }

    @Override
    public String value4() {
        return getImageUrl();
    }

    @Override
    public Edificio2Record value1(String value) {
        setNome(value);
        return this;
    }

    @Override
    public Edificio2Record value2(String value) {
        setIndirizzo(value);
        return this;
    }

    @Override
    public Edificio2Record value3(String value) {
        setSede(value);
        return this;
    }

    @Override
    public Edificio2Record value4(String value) {
        setImageUrl(value);
        return this;
    }

    @Override
    public Edificio2Record values(String value1, String value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached Edificio2Record
     */
    public Edificio2Record() {
        super(Edificio2.EDIFICIO2);
    }

    /**
     * Create a detached, initialised Edificio2Record
     */
    public Edificio2Record(String nome, String indirizzo, String sede, String imageUrl) {
        super(Edificio2.EDIFICIO2);

        setNome(nome);
        setIndirizzo(indirizzo);
        setSede(sede);
        setImageUrl(imageUrl);
        resetChangedOnNotNull();
    }
}
