/*
 * This file is generated by jOOQ.
 */
package accessibilita.genjooq.tables.records;


import accessibilita.genjooq.tables.Edificio;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class EdificioRecord extends TableRecordImpl<EdificioRecord> implements Record3<String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>Edificio.NOME</code>.
     */
    public void setNome(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>Edificio.NOME</code>.
     */
    public String getNome() {
        return (String) get(0);
    }

    /**
     * Setter for <code>Edificio.INDIRIZZO</code>.
     */
    public void setIndirizzo(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>Edificio.INDIRIZZO</code>.
     */
    public String getIndirizzo() {
        return (String) get(1);
    }

    /**
     * Setter for <code>Edificio.SEDE</code>.
     */
    public void setSede(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>Edificio.SEDE</code>.
     */
    public String getSede() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<String, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Edificio.EDIFICIO.NOME;
    }

    @Override
    public Field<String> field2() {
        return Edificio.EDIFICIO.INDIRIZZO;
    }

    @Override
    public Field<String> field3() {
        return Edificio.EDIFICIO.SEDE;
    }

    @Override
    public String component1() {
        return getNome();
    }

    @Override
    public String component2() {
        return getIndirizzo();
    }

    @Override
    public String component3() {
        return getSede();
    }

    @Override
    public String value1() {
        return getNome();
    }

    @Override
    public String value2() {
        return getIndirizzo();
    }

    @Override
    public String value3() {
        return getSede();
    }

    @Override
    public EdificioRecord value1(String value) {
        setNome(value);
        return this;
    }

    @Override
    public EdificioRecord value2(String value) {
        setIndirizzo(value);
        return this;
    }

    @Override
    public EdificioRecord value3(String value) {
        setSede(value);
        return this;
    }

    @Override
    public EdificioRecord values(String value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EdificioRecord
     */
    public EdificioRecord() {
        super(Edificio.EDIFICIO);
    }

    /**
     * Create a detached, initialised EdificioRecord
     */
    public EdificioRecord(String nome, String indirizzo, String sede) {
        super(Edificio.EDIFICIO);

        setNome(nome);
        setIndirizzo(indirizzo);
        setSede(sede);
        resetChangedOnNotNull();
    }
}
