<<<<<<< HEAD
// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
/*
package AccessiBG_ClassDiagram;



***********************************************************/
=======

>>>>>>> 2846466b3d54f334e39a854b99abb1ab25d0eb8d
package struttura;

    class Aula extends Stanza
 {
<<<<<<< HEAD
				/**
				 * 
				 */

				/**
				 * 
				 */
				public int capienza;
				/**
				 * 
				 */
				public boolean postiCarrozzina;
=======
	private int capienza;
	private boolean postiCarrozzina;
	
	public Aula() {super();}
	
	public Aula(String numero, boolean accessibile, int posti) {
		super(numero, accessibile);
		this.capienza = posti;
	}
	
	public int getCapienza() { return capienza; }
    public void setCapienza(int capienza) { this.capienza = capienza; }

    public boolean isPostiCarrozzina() { return postiCarrozzina; }
    public void setPostiCarrozzina(boolean postiCarrozzina) { 
        this.postiCarrozzina = postiCarrozzina;
    }
>>>>>>> 2846466b3d54f334e39a854b99abb1ab25d0eb8d
}
