// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Accessibilita'-ClassDiagramm;



/************************************************************/
package struttura;

/**
 * 
 */
public class Aula extends Stanza
 {
				/**
				 * 
				 */
				public undef ;
				/**
				 * 
				 */
				public int capienza;
				/**
				 * 
				 */
				public boolean postiCarrozzina;
}
