// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
/*
package AccessiBG_ClassDiagram;



***********************************************************/
package struttura;

/**
 * 
 */
public class Aula extends Stanza
 {
				/**
				 * 
				 */

				/**
				 * 
				 */
				public int capienza;
				/**
				 * 
				 */
				public boolean postiCarrozzina;
}
