<<<<<<< HEAD
// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
/*
package AccessiBG_ClassDiagram;



***********************************************************/
=======

>>>>>>> 2846466b3d54f334e39a854b99abb1ab25d0eb8d
package struttura;

public class Bagno extends Stanza
 {
	private String genere;
	private boolean bagnoDisabili;
	private boolean haAllarme;
	
	public Bagno(String numero, boolean accessibile, String genere, boolean bagnoDisabili, boolean haAllarme){
		super(numero, accessibile);
		this.genere = genere;
		this.bagnoDisabili = bagnoDisabili;
		this.haAllarme = haAllarme;
	}
	
	 public boolean isBagnoDisabili() { return bagnoDisabili; }
	 public void setBagnoDisabili(boolean bagnoDisabili) { 
	        this.bagnoDisabili = bagnoDisabili;
	 }
	 
	 public boolean isHaAllarme() { return haAllarme; }
	 public void setHaAllarme(boolean haAllarme) { this.haAllarme = haAllarme;}
	
	 public String getGenere() {return genere;}
	 public void setGenere(String genere) { this.genere = genere; }
}