// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
/*
package AccessiBG_ClassDiagram;



***********************************************************/
package struttura;

/**
 * 
 */
public class Bagno extends Stanza
 {
				/**
				 * 
				 */
				public boolean bagnoDisabili;
				/**
				 * 
				 */
				public String descrizione;
				/**
				 * 
				 */
				public boolean haAllarme;
}
