// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Accessibilita'-ClassDiagramm;



/************************************************************/
package struttura;

/**
 * 
 */
public class Bagno extends Stanza
 {
				/**
				 * 
				 */
				public boolean bagnoDisabili;
				/**
				 * 
				 */
				public String descrizione;
				/**
				 * 
				 */
				public boolean haAllarme;
}
