<<<<<<< HEAD
// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
/*
package AccessiBG_ClassDiagram;



***********************************************************/
package struttura;

/**
 * 
 */
public class Bar extends ServizioSede
=======

package struttura;


public class Bar extends Stanza
>>>>>>> 2846466b3d54f334e39a854b99abb1ab25d0eb8d
 {
	private String orario;
	
	public Bar(String descrizione, boolean accessibile, String orario) {
		super(descrizione, accessibile);
		this.orario = orario;
	}
	
	public Bar() { super(); }
	
	public String getOrario() { return orario; }
    public void setOrario(String orario) { this.orario = orario; }
}
