// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
/*
package AccessiBG_ClassDiagram;



***********************************************************/
package struttura;

/**
 * 
 */
public class Bar extends ServizioSede
 {
				/**
				 * 
				 */
				public String orario;
}
