// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Accessibilita'-ClassDiagramm;



/************************************************************/
package struttura;

/**
 * 
 */
public class Bar extends Stanza
 {
				/**
				 * 
				 */
				public String orario;
}
