// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
/*
package AccessiBG_ClassDiagram;



***********************************************************/
package struttura;

import servizi.ServizioSede;

/**
 * 
 */
public class Biblioteca extends ServizioSede
 {
				/**
				 * 
				 */
				public String tipologiaLibri;
				/**
				 * 
				 */
				public String prestito;
				/**
				 * 
				 */
				public String regolamento;
}
