// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
/************************************************************/
package struttura;

public class Edificio {
				private String indirizzo;
				private String nome;
				private String orario;
				
				private Sede sede;
				
				public Edificio() {}
				public Edificio(String nome) {
					this.nome= nome;
				}
				
				public String getIndirizzo() {return indirizzo;}
				public void setIndirizzo(String indirizzo) {this.indirizzo = indirizzo;}
				
				public String getNome() {return nome;}
				public void setNome(String nome) {this.nome = nome;}
				
				public String getOrario() {return orario;}
				public void setOrario(String orario) {this.orario = orario;}
				
				public Sede getSede() {return sede;}
				public void setSede(Sede sede) {this.sede = sede;}
}

