// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
/*
package AccessiBG_ClassDiagram;



***********************************************************/
package struttura;

import servizi.ServizioSede;

/**
 * 
 */
public class Mensa extends ServizioSede
 {
				/**
				 * 
				 */
				public String menu;
				/**
				 * 
				 */
				public String infoAllergeni;
}
