
// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
/*
package AccessiBG_ClassDiagram;



***********************************************************/

package struttura;

import Accessibilita.AccessiBG_Backend.Piano;

public class Ostacolo {
	private String descrizione;
	private TipoOstacolo tipo;
	private String posizione;
	
	private Piano piano;
	
	public Ostacolo(TipoOstacolo tipo, String descrizione, String posizione) {
        this.tipo = tipo;
        this.descrizione = descrizione;
        this.posizione = posizione;
    }
	public Ostacolo() {}
	
	public TipoOstacolo getTipo() { return tipo; }
    public void setTipo(TipoOstacolo tipo) { this.tipo = tipo; }

    public String getDescrizione() { return descrizione; }
    public void setDescrizione(String descrizione) { this.descrizione = descrizione; }

    public String getPosizione() { return posizione; }
    public void setPosizione(String posizione) { this.posizione = posizione; }
    
    public Piano getPiano() { return piano; }
    public void setPiano(Piano piano) { this.piano = piano; }
}
