
// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
/*
package AccessiBG_ClassDiagram;
***********************************************************/
package struttura;
import servizi.ServizioSede;

public class Parcheggio extends ServizioSede {

	private boolean postiDisabili;
	private TipoParcheggio tipo;
	private String nome;
	private String indirizzo;
	private String facolta;
	private String pathFoto;
	
	public Parcheggio(String nome, TipoParcheggio tipo, boolean postiDisabili, String indirizzo, String pathFoto, String facolta) {
        this.nome = nome;
        this.tipo = tipo;
        this.postiDisabili = postiDisabili;
        this.indirizzo = indirizzo;
        this.facolta=facolta;
        this.pathFoto=pathFoto;
    }
	
	public boolean getPostiDisabili() { return postiDisabili; }
//    public void setPostiDisabili(boolean postiDisabili) { this.postiDisabili = postiDisabili; }
	
    public TipoParcheggio getTipo() {return tipo;}
//    public void setTipo(TipoParcheggio tipo) {this.tipo = tipo;}
    
    public String getNome() { return nome; }
//    public void setNome(String nome) { this.nome = nome; }
    
    public String getIndirizzo() { return indirizzo; }
//    public void setPosizione(String posizione) { this.indirizzo = posizione; }

	public String getFacolta() {return facolta;}

	public String getPathFoto() {return pathFoto;}
}
