// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Accessibilita'-ClassDiagramm;



/************************************************************/
package struttura;

/**
 * 
 */
public class Parcheggio {
				/**
				 * 
				 */
				public boolean discoOrario;
				/**
				 * 
				 */
				public boolean pDisabili;
				/**
				 * 
				 */
				public TipoParcheggio tipoParcheggio;
}
