// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
/*
package AccessiBG_ClassDiagram;



***********************************************************/
package struttura;

/**
 * 
 */
public class Parcheggio extends ServizioSede {
				/**
				 * 
				 */
				public boolean discoOrario;
				/**
				 * 
				 */
				public boolean pDisabili;
				/**
				 * 
				 */
				public TipoParcheggio tipoParcheggio;
}
