
// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
/*
package AccessiBG_ClassDiagram;



***********************************************************/

package struttura;

import java.util.ArrayList;
import java.util.List;

import Accessibilita.AccessiBG_Backend.Edificio;

public class Piano {

	public int numero;
	private String descrizione;
	private List<Distributore> distributori = new ArrayList<>();
	private List<Stanza> stanze = new ArrayList<>();
	private List<Ostacolo> ostacoli = new ArrayList<>();
	private Edificio edificio;
	
	public Piano() {}
	
	public Piano(int numero, String descrizione) {
		this.numero = numero;
		this.descrizione = descrizione;
	}
	
	public void addDistributore(Distributore d) {
		this.distributori.add(d);
		d.setPiano(this);
	}
	
	public void addStanza(Stanza s) {
			this.stanze.add(s);
			s.setPiano(this);
	}
	public void addOstacolo(Ostacolo o) {
        this.ostacoli.add(o);
        o.setPiano(this);
    }
	
	public List<Distributore> getDistributori() {return distributori;}
    public void setDistributori(List<Distributore> distributori) {this.distributori = distributori;}
    
    public List<Stanza> getStanze() { return stanze; }
    public void setStanze(List<Stanza> stanze) { this.stanze = stanze; }
    
    public List<Ostacolo> getOstacoli() { return ostacoli; }
    public void setOstacoli(List<Ostacolo> ostacoli) { this.ostacoli = ostacoli; }
	
	public Edificio getEdificio() {return edificio;}
	public void setEdificio(Edificio edificio) {this.edificio = edificio;}
	
	public int getNumero() { return numero; }
    public void setNumero(int numero) { this.numero = numero; }

    public String getDescrizione() { return descrizione; }
    public void setDescrizione(String descrizione) { this.descrizione = descrizione;}
}
