// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------


/************************************************************/
package struttura;

public class PuntiDiAccesso {

				private String nome;
				private boolean accessibile;
				private String descrizione;
				
				public PuntiDiAccesso() {}
				
				public PuntiDiAccesso(String nome, boolean accessibile) {
					this.nome = nome;
					this.accessibile = accessibile;
				}
				
				public String getNome() {return nome;}
				public void setNome(String nome) {this.nome = nome;}
				
				public boolean IsAccessibile() {return accessibile;}
				public void setAccessibile(boolean accessibile) {this.accessibile = accessibile;}
				
				public String getDescrizione() {return descrizione;}
				public void setDescrizione(String descrizione) {this.descrizione = descrizione;}
}
