// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Accessibilita'-ClassDiagramm;



/************************************************************/
package struttura;

/**
 * 
 */
public class Segreteria {
				/**
				 * 
				 */
				public String orario;
	/**
	 * 
	 */
	public void getSede() {
	}
}
