// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
/*
package AccessiBG_ClassDiagram;



***********************************************************/
package struttura;

import servizi.ServizioSede;

/**
 * 
 */
public class Segreteria extends ServizioSede {
				/**
				 * 
				 */
				public String orario;
	/**
	 * 
	 */

}
