// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Accessibilita'-ClassDiagramm;



/************************************************************/
package struttura;

/**
 * 
 */
public class ServiziRistoro {
				/**
				 * 
				 */
				public ServiziPiano tipo;
				/**
				 * 
				 */
				public boolean fuoriServizio;
				/**
				 * 
				 */
				public String accesPulsantiera;
	/**
	 * 
	 */
	public void segnalaGuasto() {
	}
}
