// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Accessibilita'-ClassDiagramm;



/************************************************************/
package struttura;

/**
 * 
 */
public enum ServiziPiano {
	/**
	 * 
	 */
	MACCHINETTE,
	/**
	 * 
	 */
	DISTRIBUTOREACQUA,
	/**
	 * 
	 */
	ASCENSORE
	;
}
