// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
/*
package AccessiBG_ClassDiagram;



***********************************************************/
package struttura;

/**
 * 
 */
public class Stanza {
				/**
				 * 
				 */
				public String nome;
				/**
				 * 
				 */
				public String descrizione;
}
