
// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
/*
package AccessiBG_ClassDiagram;



***********************************************************/

package struttura;

public abstract class Stanza {
				
	private String nome;
	private String descrizione;
	private boolean accessibile;
	private Piano piano;
	
	public Stanza(String nome, boolean accessibile) {
		this.nome = nome;
		this.accessibile = accessibile;
	}
	
	public Stanza() {}
	
	public String getNome() {return nome;}
    public void setNome(String nome) { this.nome = nome; }

    public boolean isAccessibile() { return accessibile; }
    public void setAccessibile(boolean accessibile) { this.accessibile = accessibile;}
    
    public String getDescrizione() {return descrizione;}
    public void setDescrizione(String descrizione) { this.descrizione = descrizione; }
    
    public Piano getPiano() { return piano; }
    public void setPiano(Piano piano) { this.piano = piano; }
}
