// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
/*
package AccessiBG_ClassDiagram;



***********************************************************/
package struttura;

/**
 * 
 */
public enum TipoParcheggio {
	/**
	 * 
	 */
	LIBERO ,
	/**
	 * 
	 */
	PAGAMENTO ,
	/**
	 * 
	 */
	DISCO
	;
}
