<<<<<<< HEAD
// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
/*
package AccessiBG_ClassDiagram;



***********************************************************/
=======

>>>>>>> 2846466b3d54f334e39a854b99abb1ab25d0eb8d
package struttura;

public class UfficioDocenti extends Stanza
 {
	private String docente;
	
	public UfficioDocenti(String descrizione, boolean accessibile, String docente) {
		super(descrizione, accessibile);
		this.docente = docente;
	}
	
	public UfficioDocenti() {super();}
	
	public String getDocente() { return docente; }
    public void setDocente(String docente) { this.docente = docente; }
}
