
// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
/*
package AccessiBG_ClassDiagram;



***********************************************************/

package struttura;

public class UfficioDocenti extends Stanza
 {
	private String docente;
	
	public UfficioDocenti(String descrizione, boolean accessibile, String docente) {
		super(descrizione, accessibile);
		this.docente = docente;
	}
	
	public UfficioDocenti() {super();}
	
	public String getDocente() { return docente; }
    public void setDocente(String docente) { this.docente = docente; }
}
