// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
/*
package AccessiBG_ClassDiagram;



***********************************************************/
package struttura;

/**
 * 
 */
public class UfficioDocenti extends Stanza
 {
				/**
				 * 
				 */
				public String nome;
				/**
				 * 
				 */
				public String docente;
}
