// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Accessibilita'-ClassDiagramm;



/************************************************************/
/**
 * 
 */
public class Biblioteca extends Edificio
 {
				/**
				 * 
				 */
				public String tipologiaLibri;
				/**
				 * 
				 */
				public String prestito;
				/**
				 * 
				 */
				public String regolamento;
}
