// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Accessibilita'-ClassDiagramm;



/************************************************************/
/**
 * 
 */
public class Edificio {
				/**
				 * 
				 */
				public String indirizzo;
				/**
				 * 
				 */
				public String nome;
				/**
				 * 
				 */
				public String orario;
}
