// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Accessibilita'-ClassDiagramm;



/************************************************************/
/**
 * 
 */
public class Mensa extends Edificio
 {
				/**
				 * 
				 */
				public String menu;
				/**
				 * 
				 */
				public String infoAllergeni;
}
