// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Accessibilita'-ClassDiagramm;



/************************************************************/
/**
 * 
 */
public class Piano {
				/**
				 * 
				 */
				public int numero;
	/**
	 * 
	 */
	public void getStanza() {
	}
}
