// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Accessibilita'-ClassDiagramm;



/************************************************************/
/**
 * 
 */
public class PuntiDiAccesso {
				/**
				 * 
				 */
				public String Posizione;
				/**
				 * 
				 */
				public boolean rampa;
				/**
				 * 
				 */
				public boolean scala;
				/**
				 * 
				 */
				public boolean portaSpinta;
				/**
				 * 
				 */
				public boolean portaAutomatica;
}
