// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Accessibilita'-ClassDiagramm;



/************************************************************/
/**
 * 
 */
public class Sede {
				/**
				 * 
				 */
				public int indirizzo;
				/**
				 * 
				 */
				public String facolta;
				/**
				 * 
				 */
				public String nome;
	/**
	 * 
	 */
	public void getEdificio() {
	}
}
