// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Accessibilita'-ClassDiagramm;



/************************************************************/
/**
 * 
 */
public class Stanza {
				/**
				 * 
				 */
				public String nome;
				/**
				 * 
				 */
				public String descrizione;
}
