// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Accessibilita'-ClassDiagramm;



/************************************************************/
/**
 * 
 */
public enum TipoParcheggio {
	/**
	 * 
	 */
	LIBERO,
	/**
	 * 
	 */
	A PAGAMENTO,
	/**
	 * 
	 */
	DISCO ORARIO
	;
}
