// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Accessibilita'-ClassDiagramm;



/************************************************************/
/**
 * 
 */
public class UfficioDocenti extends Stanza
 {
				/**
				 * 
				 */
				public String nome;
				/**
				 * 
				 */
				public String docente;
}
