// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
/*
package AccessiBG_ClassDiagram;



***********************************************************/
package struttura;

import servizi.ServizioSede;

/**
 * 
 */
public class Laboratorio extends ServizioSede {
	
}
