/*
 * This file is generated by jOOQ.
 */
package accessibilita.genjooq.tables;


import accessibilita.genjooq.DefaultSchema;
import accessibilita.genjooq.tables.records.Edificio2Record;

import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function4;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Edificio2 extends TableImpl<Edificio2Record> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>Edificio2</code>
     */
    public static final Edificio2 EDIFICIO2 = new Edificio2();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Edificio2Record> getRecordType() {
        return Edificio2Record.class;
    }

    /**
     * The column <code>Edificio2.NOME</code>.
     */
    public final TableField<Edificio2Record, String> NOME = createField(DSL.name("NOME"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>Edificio2.INDIRIZZO</code>.
     */
    public final TableField<Edificio2Record, String> INDIRIZZO = createField(DSL.name("INDIRIZZO"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>Edificio2.SEDE</code>.
     */
    public final TableField<Edificio2Record, String> SEDE = createField(DSL.name("SEDE"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>Edificio2.IMAGE_URL</code>.
     */
    public final TableField<Edificio2Record, String> IMAGE_URL = createField(DSL.name("IMAGE_URL"), SQLDataType.CLOB, this, "");

    private Edificio2(Name alias, Table<Edificio2Record> aliased) {
        this(alias, aliased, null);
    }

    private Edificio2(Name alias, Table<Edificio2Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>Edificio2</code> table reference
     */
    public Edificio2(String alias) {
        this(DSL.name(alias), EDIFICIO2);
    }

    /**
     * Create an aliased <code>Edificio2</code> table reference
     */
    public Edificio2(Name alias) {
        this(alias, EDIFICIO2);
    }

    /**
     * Create a <code>Edificio2</code> table reference
     */
    public Edificio2() {
        this(DSL.name("Edificio2"), null);
    }

    public <O extends Record> Edificio2(Table<O> child, ForeignKey<O, Edificio2Record> key) {
        super(child, key, EDIFICIO2);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Edificio2 as(String alias) {
        return new Edificio2(DSL.name(alias), this);
    }

    @Override
    public Edificio2 as(Name alias) {
        return new Edificio2(alias, this);
    }

    @Override
    public Edificio2 as(Table<?> alias) {
        return new Edificio2(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Edificio2 rename(String name) {
        return new Edificio2(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Edificio2 rename(Name name) {
        return new Edificio2(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Edificio2 rename(Table<?> name) {
        return new Edificio2(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<String, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function4<? super String, ? super String, ? super String, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function4<? super String, ? super String, ? super String, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
