/*
 * This file is generated by jOOQ.
 */
package accessibilita.genjooq;


import accessibilita.genjooq.tables.Edificio;
import accessibilita.genjooq.tables.Edificio2;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>Edificio</code>.
     */
    public static final Edificio EDIFICIO = Edificio.EDIFICIO;

    /**
     * The table <code>Edificio2</code>.
     */
    public static final Edificio2 EDIFICIO2 = Edificio2.EDIFICIO2;
}
